---

- name: "Set timezone to {{ timezone_zone }}"
  copy: content="{{ timezone_zone }}"
        dest=/etc/timezone
        owner=root
        group=root
        mode=0644
        backup=yes
  notify:
    - update timezone
