---

- name: restart sshd
  service: name={{ sshd }} state=restarted


- name: restart nptd
  service: name={{ nptd }} state=restarted

- name: update timezone
  command: dpkg-reconfigure --frontend noninteractive tzdata
